# Generated by Django 4.0.3 on 2022-03-28 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import plataforma.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_album', models.CharField(max_length=30)),
                ('carregado_em', models.DateField(default=django.utils.timezone.now)),
                ('logo_do_album', models.FileField(upload_to=plataforma.models.user_directory_path)),
                ('genero_do_album', models.CharField(max_length=30)),
                ('artista_do_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albuns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_musica', models.CharField(max_length=40)),
                ('arquivo_de_musica', models.FileField(upload_to=plataforma.models.user_directory_path_song)),
                ('album_da_musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musicas', to='plataforma.album')),
            ],
        ),
    ]
